Repository carrot-foundation/methodology-rules, pull requests merged in 2024-09, with the labels that each got.

#60 feat: add origin_state and recycler_name in summary [CARROT-1336]
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.types.ts
Labels: feature, priority: high

#62 feat: update fields in summary [CARROT-1336]
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.types.ts
Labels: feature, priority: high

#61 Change NFT traits and other attributes
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.spec.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.ts
Labels: enhancement

#63 fix: remove certificateValue from nft-metadata-selection
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.dto.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.spec.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.stubs.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.types.ts
  libs/methodologies/bold/types/src/enum.types.ts
Labels: feature

#64 Improve formatWeight helper
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.spec.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.ts
Labels: enhancement

#67 feat(rule): update the HOMOLOGATION_DUE_DATE formate
  libs/methodologies/bold/processors/src/geolocation-precision-processor.spec.ts
Labels: feature

#68 feat: remove old mass-certificate rules [CARROT-1345]
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/.eslintrc.js
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/README.md
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/jest.config.ts
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/package.json
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/project.json
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/src/lambda.ts
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/src/lib/mass-validation-document-status.processor.e2e.spec.ts
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/src/lib/mass-validation-document-status.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/src/lib/mass-validation-document-status.processor.ts
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/tsconfig.build.json
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/tsconfig.eslint.json
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/tsconfig.json
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document-status/tsconfig.spec.json
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/.eslintrc.js
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/README.md
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/jest.config.ts
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/package.json
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/project.json
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/src/lambda.ts
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/src/lib/mass-validation-document.processor.e2e.spec.ts
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/src/lib/mass-validation-document.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/src/lib/mass-validation-document.processor.ts
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/src/lib/mass-validation-document.stubs.ts
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/tsconfig.build.json
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/tsconfig.eslint.json
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/tsconfig.json
  apps/methodologies/bold/rule-processors/mass-certificate/mass-validation-document/tsconfig.spec.json
Labels: feature

#69 feature/add new NFT trait
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.ts
Labels: feature

#71 feat: add new subtype to document-subtype rule
  apps/methodologies/bold/rule-processors/mass/document-subtype/src/lib/document-subtype.processor.ts
Labels: feature

#72 feat: add new MassSubtype
  apps/methodologies/bold/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.constants.ts
  libs/methodologies/bold/types/src/enum.types.ts
Labels: feature

#74 feat: add collection name and mass origin city in NFT metadata
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.dto.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.ts
Labels: feature

#75 feat: add collection name and mass origin city in NFT summary
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.types.ts
Labels: feature

#76 feat: add possible timeout alert for rules in sentry [CARROT-488]
  libs/shared/lambda/wrapper/src/lambda-wrapper.ts
Labels: feature

#77 fix: remove unnecessary config [CARROT-488]
  libs/shared/lambda/wrapper/src/lambda-wrapper.ts
Labels: fix
