Repository carrot-foundation/methodology-rules, pull requests merged in 2024-06, with the labels that each got.

#12 Create readme file for all rules [CARROT-868]
  LICENSE
  apps/methodologies/bold/rule-processors/certificate/mass-document-type/README.md
  apps/methodologies/bold/rule-processors/certificate/mass-recycler-actor/README.md
  apps/methodologies/bold/rule-processors/certificate/mass-validation-document-status/README.md
  apps/methodologies/bold/rule-processors/certificate/mass-validation-document/README.md
  apps/methodologies/bold/rule-processors/certificate/rewards-distribution/README.md
  apps/methodologies/bold/rule-processors/mass/cdf-address/README.md
  apps/methodologies/bold/rule-processors/mass/cdf-attachment-name/README.md
  apps/methodologies/bold/rule-processors/mass/cdf-attachment-verification/README.md
  apps/methodologies/bold/rule-processors/mass/cdf-fields/README.md
  apps/methodologies/bold/rule-processors/mass/cdf-reason-dismissal/README.md
  apps/methodologies/bold/rule-processors/mass/document-category/README.md
  apps/methodologies/bold/rule-processors/mass/document-measurement-unit/README.md
  apps/methodologies/bold/rule-processors/mass/document-subtype/README.md
  apps/methodologies/bold/rule-processors/mass/document-type/README.md
  apps/methodologies/bold/rule-processors/mass/document-value/README.md
  apps/methodologies/bold/rule-processors/mass/driver-internal-id/README.md
  apps/methodologies/bold/rule-processors/mass/drop-off-geolocation-precision/README.md
  apps/methodologies/bold/rule-processors/mass/drop-off-move/README.md
  apps/methodologies/bold/rule-processors/mass/end-event-value/README.md
  apps/methodologies/bold/rule-processors/mass/events-time-span/README.md
  apps/methodologies/bold/rule-processors/mass/has-cdf/README.md
  apps/methodologies/bold/rule-processors/mass/has-mtr/README.md
  apps/methodologies/bold/rule-processors/mass/invoice-fields/README.md
  apps/methodologies/bold/rule-processors/mass/maximum-distance/README.md
  apps/methodologies/bold/rule-processors/mass/move-type/README.md
  apps/methodologies/bold/rule-processors/mass/mtr-attachment-name/README.md
  apps/methodologies/bold/rule-processors/mass/mtr-attachment-verification/README.md
  apps/methodologies/bold/rule-processors/mass/mtr-reason-dismissal/README.md
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/README.md
  apps/methodologies/bold/rule-processors/mass/numeric-weight-values/README.md
  apps/methodologies/bold/rule-processors/mass/pick-up-geolocation-precision/README.md
  apps/methodologies/bold/rule-processors/mass/pick-up-move/README.md
  apps/methodologies/bold/rule-processors/mass/primary-participant-address/README.md
  apps/methodologies/bold/rule-processors/mass/primary-participant/README.md
  apps/methodologies/bold/rule-processors/mass/recycler-actor/README.md
  apps/methodologies/bold/rule-processors/mass/same-recycler-and-drop-off-addresses/README.md
  apps/methodologies/bold/rule-processors/mass/same-source-and-pick-up-addresses/README.md
  apps/methodologies/bold/rule-processors/mass/source-actor/README.md
  apps/methodologies/bold/rule-processors/mass/vehicle-description/README.md
  apps/methodologies/bold/rule-processors/mass/vehicle-license-plate/README.md
  apps/methodologies/bold/rule-processors/mass/vehicle-type/README.md
  apps/methodologies/bold/rule-processors/mass/waste-origin-identified/README.md
  apps/methodologies/bold/rule-processors/mass/weighing-fields/README.md
  apps/methodologies/bold/rule-processors/offer/nft-metadata-selection/README.md
  apps/methodologies/bold/rule-processors/offer/rewards-distribution/README.md
Labels: chore

#15 fix: change the required actors verification
  apps/methodologies/bold/rule-processors/certificate/rewards-distribution/src/lib/rewards-distribution.processor.errors.ts
  apps/methodologies/bold/rule-processors/certificate/rewards-distribution/src/lib/rewards-distribution.processor.spec.ts
  apps/methodologies/bold/rule-processors/certificate/rewards-distribution/src/lib/rewards-distribution.processor.ts
Labels: fix

#14 Adjust net weight verification rule [CARROT-930]
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.processor.ts
  libs/methodologies/bold/testing/src/documents/rejected-mass-document.ts
Labels: feature, priority: high

#18 chore: configure coderabbit to AI review
  .coderabbit.yaml
Labels: chore

#22 feat(rule): :sparkles: update geolocation-precision rule to validate app-gps values
  libs/methodologies/bold/processors/src/geolocation-precision-processor.spec.ts
  libs/methodologies/bold/processors/src/geolocation-precision-processor.ts
  libs/methodologies/bold/processors/src/geolocation-precision.helpers.ts
  libs/methodologies/bold/types/src/enum.types.ts
  libs/shared/types/src/number.types.ts
Labels: feature

#26 feat: add enabled and environment options for sentry lambda init
  libs/shared/lambda/wrapper/src/lambda-wrapper.ts
Labels: feature

#27 feat(rule): :sparkles: update the result comment in evaluteResult method
  libs/methodologies/bold/processors/src/geolocation-precision-processor.spec.ts
  libs/methodologies/bold/processors/src/geolocation-precision-processor.ts
Labels: feature

#31 feat: change Carrot PROD_SIMULATION id
  libs/methodologies/bold/utils/src/rule-processors.constants.ts
Labels: feature

#33 Add LGPL-3.0 license [CARROT-917]
  LICENSE
  package.json
Labels: chore
