Repository carrot-foundation/methodology-rules, pull requests merged in 2024-11, with the labels that each got.

#81 Fix weight attributes extraction
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.utils.ts
  libs/shared/helpers/src/string.helpers.spec.ts
  libs/shared/helpers/src/string.helpers.ts
Labels: 1 min review

#83 Fix extractNumberFromString
  libs/shared/helpers/src/string.helpers.spec.ts
  libs/shared/helpers/src/string.helpers.ts
Labels: 1 min review

#84 Improve rewards distribution error handling
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.processor.spec.ts
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.processor.ts
Labels: ⏳ Waiting for 1 reviewer, 10 min review

#82 Update BOLD methodology name on readme
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/README.md
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/README.md
  apps/methodologies/bold/rule-processors/mass-certificate/mass-audit-document-status/README.md
  apps/methodologies/bold/rule-processors/mass-certificate/mass-audit-document/README.md
  apps/methodologies/bold/rule-processors/mass-certificate/mass-document-type/README.md
  apps/methodologies/bold/rule-processors/mass-certificate/mass-recycler-actor/README.md
  apps/methodologies/bold/rule-processors/mass-certificate/rewards-distribution/README.md
  apps/methodologies/bold/rule-processors/mass/cdf-address/README.md
  apps/methodologies/bold/rule-processors/mass/cdf-attachment-name/README.md
  apps/methodologies/bold/rule-processors/mass/cdf-attachment-verification/README.md
  apps/methodologies/bold/rule-processors/mass/cdf-fields/README.md
  apps/methodologies/bold/rule-processors/mass/cdf-reason-dismissal/README.md
  apps/methodologies/bold/rule-processors/mass/document-category/README.md
  apps/methodologies/bold/rule-processors/mass/document-measurement-unit/README.md
  apps/methodologies/bold/rule-processors/mass/document-subtype/README.md
  apps/methodologies/bold/rule-processors/mass/document-type/README.md
  apps/methodologies/bold/rule-processors/mass/document-value/README.md
  apps/methodologies/bold/rule-processors/mass/driver-internal-id/README.md
  apps/methodologies/bold/rule-processors/mass/drop-off-geolocation-precision/README.md
  apps/methodologies/bold/rule-processors/mass/drop-off-move/README.md
  apps/methodologies/bold/rule-processors/mass/event-value/README.md
  apps/methodologies/bold/rule-processors/mass/events-time-span/README.md
  apps/methodologies/bold/rule-processors/mass/has-cdf/README.md
  apps/methodologies/bold/rule-processors/mass/has-mtr/README.md
  apps/methodologies/bold/rule-processors/mass/invoice-fields/README.md
  apps/methodologies/bold/rule-processors/mass/mandatory-metadata/README.md
  apps/methodologies/bold/rule-processors/mass/maximum-distance/README.md
  apps/methodologies/bold/rule-processors/mass/move-type/README.md
  apps/methodologies/bold/rule-processors/mass/mtr-attachment-name/README.md
  apps/methodologies/bold/rule-processors/mass/mtr-attachment-verification/README.md
  apps/methodologies/bold/rule-processors/mass/mtr-reason-dismissal/README.md
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/README.md
  apps/methodologies/bold/rule-processors/mass/numeric-weight-values/README.md
  apps/methodologies/bold/rule-processors/mass/pick-up-geolocation-precision/README.md
  apps/methodologies/bold/rule-processors/mass/primary-participant-address/README.md
  apps/methodologies/bold/rule-processors/mass/primary-participant/README.md
  apps/methodologies/bold/rule-processors/mass/recycler-actor/README.md
  apps/methodologies/bold/rule-processors/mass/same-recycler-and-drop-off-addresses/README.md
  apps/methodologies/bold/rule-processors/mass/same-source-and-pick-up-addresses/README.md
  apps/methodologies/bold/rule-processors/mass/source-actor/README.md
  apps/methodologies/bold/rule-processors/mass/vehicle-description/README.md
  apps/methodologies/bold/rule-processors/mass/vehicle-license-plate/README.md
  apps/methodologies/bold/rule-processors/mass/vehicle-type/README.md
  apps/methodologies/bold/rule-processors/mass/waste-origin-identified/README.md
  apps/methodologies/bold/rule-processors/mass/weighing-fields/README.md
Labels: Safe Change, 20 min review

#85 Fix rewards distribution amount decimals places
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/__snapshots__/rewards-distribution.helpers.spec.ts.snap
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.helpers.spec.ts
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.helpers.ts
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.processor.e2e.spec.ts
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.stubs.ts
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.test.data.ts
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.test.helpers.ts
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.types.ts
  libs/shared/helpers/src/math.helpers.spec.ts
  libs/shared/helpers/src/math.helpers.ts
  libs/shared/testing/src/stubs/__tests__/number.stubs.spec.ts
  libs/shared/testing/src/stubs/index.ts
  libs/shared/testing/src/stubs/number.stubs.ts
  libs/shared/types/src/number.types.ts
Labels: ⏳ Waiting for 2 reviewers, 20 min review

#87 fix/metadata selection image
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.spec.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.processor.e2e.spec.ts
  libs/methodologies/bold/getters/src/document.getters.spec.ts
  libs/methodologies/bold/getters/src/document.getters.ts
Labels: fix, 1 min review

#86 Fix jest text coverage reporter config
  jest.preset.js
Labels: 1 min review

#88 Remove european format from extractNumberFromString
  libs/shared/helpers/src/string.helpers.spec.ts
  libs/shared/helpers/src/string.helpers.ts
Labels: 1 min review

#89 Add result comments to net weight verificaion rule
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/__snapshots__/net-weight-verification.processor.spec.ts.snap
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.processor.ts
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.stubs.ts
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.utils.ts
Labels: ⏳ Waiting for 1 reviewer, 20 min review

#90 chore: temporary log in nft-metadata-selection
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.processor.ts
Labels: chore, ⏳ Waiting for 1 reviewer, 1 min review

#92 chore: remove temporary log in nft-metadata-selection
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.processor.ts
  pnpm-lock.yaml
Labels: chore

#93 chore: update pnpm-lock
  .github/actions/install-node-dependencies/action.yaml
  package.json
  pnpm-lock.yaml
Labels: chore, ⏳ Waiting for 1 reviewer, 1 min review

#94 [STACKED] chore: update non-major lib version [CARROT-1587]
  package.json
  pnpm-lock.yaml
Labels: chore, 1 min review

#95 [STACKED] chore/upgrade node
  .gitignore
  .npmrc
  .nvmrc
  .tool-versions
  libs/shared/s3-bucket/src/s3-bucket.repository.spec.ts
  package.json
Labels: chore, 1 min review

#91 chore: update lambdas metadata [CARROT-1394]
  .github/workflows/deploy.yaml
  package.json
  scripts/upload-lambda.sh
  scripts/upload-lambdas-and-metadata.sh
Labels: 1 min review

#97 fix: rename metadata path for checksum [CARROT-1394]
  .gitignore
  libs/shared/lambda/wrapper/src/lambda-wrapper.ts
  nx.json
  scripts/upload-lambda.sh
  scripts/upload-lambdas-and-metadata.sh
Labels: 1 min review

#98 fix: fix checksum in upload metadata script [CARROT-1394]
  .github/workflows/deploy.yaml
  libs/shared/lambda/wrapper/src/lambda-wrapper.ts
  scripts/upload-lambdas-and-metadata.sh
Labels: fix, 1 min review

#99 fix: add BigNumber in subtraction to get correct result
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/__snapshots__/net-weight-verification.processor.spec.ts.snap
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.processor.ts
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.stubs.ts
Labels: fix, ⏳ Waiting for 1 reviewer, 1 min review

#101 feat: add snapshot tests for result comments [CARROT-1593]
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/__snapshots__/net-weight-verification.processor.spec.ts.snap
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.processor.ts
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/src/lib/net-weight-verification.stubs.ts
Labels: feature, ⏳ Waiting for 1 reviewer, 10 min review
