Repository carrot-foundation/methodology-rules, pull requests merged in 2024-05, with the labels that each got.

#4 feat: get methodology slug from certificate audit [CARROT-714]
  apps/methodologies/bold/rule-processors/certificate/mass-document-type/src/lib/mass-document-type.processor.spec.ts
  apps/methodologies/bold/rule-processors/certificate/mass-recycler-actor/src/lib/recycler-actor.processor.spec.ts
  apps/methodologies/bold/rule-processors/certificate/mass-validation-document-status/src/lib/mass-validation-document-status.processor.spec.ts
  apps/methodologies/bold/rule-processors/certificate/mass-validation-document/src/lib/mass-validation-document.processor.e2e.spec.ts
  apps/methodologies/bold/rule-processors/certificate/mass-validation-document/src/lib/mass-validation-document.processor.spec.ts
  apps/methodologies/bold/rule-processors/certificate/mass-validation-document/src/lib/mass-validation-document.processor.ts
  apps/methodologies/bold/rule-processors/certificate/mass-validation-document/src/lib/mass-validation-document.stubs.ts
  apps/methodologies/bold/rule-processors/certificate/rewards-distribution/src/lib/rewards-distribution.processor.spec.ts
  apps/methodologies/bold/rule-processors/offer/nft-metadata-selection/src/lib/nft-metadata-selection.processor.spec.ts
  apps/methodologies/bold/rule-processors/offer/rewards-distribution/src/lib/rewards-distribution.processor.spec.ts
  libs/methodologies/bold/getters/src/event.getters.spec.ts
  libs/methodologies/bold/io-helpers/src/abstract-document-query.service.ts
  libs/methodologies/bold/io-helpers/src/document-query.service.types.ts
  libs/methodologies/bold/io-helpers/src/testing.helpers.ts
  libs/methodologies/bold/processors/src/geolocation-precision-processor.spec.ts
  libs/methodologies/bold/testing/src/stubs/document.stubs.ts
  libs/methodologies/bold/utils/src/rule-processors.constants.ts
  libs/shared/helpers/src/index.ts
  libs/shared/helpers/src/methodology.helpers.spec.ts
  libs/shared/helpers/src/methodology.helpers.ts
  libs/shared/lambda/wrapper/src/lambda-wrapper.spec.ts
  libs/shared/lambda/wrapper/src/lambda-wrapper.ts
Labels: enhancement

#5 feat: rename returned document in documentQuery [CARROT-714]
  apps/methodologies/bold/rule-processors/certificate/mass-validation-document/src/lib/mass-validation-document.processor.ts
  libs/methodologies/bold/io-helpers/src/abstract-document-query.service.ts
  libs/methodologies/bold/io-helpers/src/document-query.service.types.ts
  libs/methodologies/bold/io-helpers/src/testing.helpers.ts
Labels: enhancement

#9 fix: fix the project schema path in project files
  apps/methodologies/bold/rule-processors/certificate/mass-document-type/project.json
  apps/methodologies/bold/rule-processors/certificate/mass-recycler-actor/project.json
  apps/methodologies/bold/rule-processors/certificate/mass-validation-document-status/project.json
  apps/methodologies/bold/rule-processors/certificate/mass-validation-document/project.json
  apps/methodologies/bold/rule-processors/mass/cdf-address/project.json
  apps/methodologies/bold/rule-processors/mass/cdf-attachment-name/project.json
  apps/methodologies/bold/rule-processors/mass/cdf-attachment-verification/project.json
  apps/methodologies/bold/rule-processors/mass/cdf-fields/project.json
  apps/methodologies/bold/rule-processors/mass/cdf-reason-dismissal/project.json
  apps/methodologies/bold/rule-processors/mass/document-category/project.json
  apps/methodologies/bold/rule-processors/mass/document-measurement-unit/project.json
  apps/methodologies/bold/rule-processors/mass/document-subtype/project.json
  apps/methodologies/bold/rule-processors/mass/document-type/project.json
  apps/methodologies/bold/rule-processors/mass/document-value/project.json
  apps/methodologies/bold/rule-processors/mass/driver-internal-id/project.json
  apps/methodologies/bold/rule-processors/mass/drop-off-geolocation-precision/project.json
  apps/methodologies/bold/rule-processors/mass/drop-off-move/project.json
  apps/methodologies/bold/rule-processors/mass/end-event-value/project.json
  apps/methodologies/bold/rule-processors/mass/events-time-span/project.json
  apps/methodologies/bold/rule-processors/mass/has-cdf/project.json
  apps/methodologies/bold/rule-processors/mass/has-mtr/project.json
  apps/methodologies/bold/rule-processors/mass/invoice-fields/project.json
  apps/methodologies/bold/rule-processors/mass/maximum-distance/project.json
  apps/methodologies/bold/rule-processors/mass/move-type/project.json
  apps/methodologies/bold/rule-processors/mass/mtr-attachment-name/project.json
  apps/methodologies/bold/rule-processors/mass/mtr-attachment-verification/project.json
  apps/methodologies/bold/rule-processors/mass/mtr-reason-dismissal/project.json
  apps/methodologies/bold/rule-processors/mass/net-weight-verification/project.json
  apps/methodologies/bold/rule-processors/mass/numeric-weight-values/project.json
  apps/methodologies/bold/rule-processors/mass/pick-up-geolocation-precision/project.json
  apps/methodologies/bold/rule-processors/mass/pick-up-move/project.json
  apps/methodologies/bold/rule-processors/mass/primary-participant-address/project.json
  apps/methodologies/bold/rule-processors/mass/primary-participant/project.json
  apps/methodologies/bold/rule-processors/mass/recycler-actor/project.json
  apps/methodologies/bold/rule-processors/mass/same-recycler-and-drop-off-addresses/project.json
  apps/methodologies/bold/rule-processors/mass/same-source-and-pick-up-addresses/project.json
  apps/methodologies/bold/rule-processors/mass/source-actor/project.json
  apps/methodologies/bold/rule-processors/mass/vehicle-description/project.json
  apps/methodologies/bold/rule-processors/mass/vehicle-license-plate/project.json
  apps/methodologies/bold/rule-processors/mass/vehicle-type/project.json
  apps/methodologies/bold/rule-processors/mass/waste-origin-identified/project.json
  apps/methodologies/bold/rule-processors/mass/weighing-fields/project.json
Labels: chore

#11 feat(rule): :sparkles: updae the CARRTOT_PARTICIPANTS ids
  libs/methodologies/bold/utils/src/rule-processors.constants.ts
Labels: feature

#13 fix: update the DocumentEventActorType.APPOINTED_NGO
  libs/methodologies/bold/types/src/enum.types.ts
Labels: feature
