Repository carrot-foundation/methodology-rules, pull requests merged in 2024-07, with the labels that each got.

#35 feat(rule): :sparkles: get event with DROP_OFF metadata in events-time-span rule
  apps/methodologies/bold/rule-processors/mass/events-time-span/src/lib/events-time-span.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/events-time-span/src/lib/events-time-span.processor.ts
Labels: feature

#36 feat(rule): update pick-up move rule [CARROT-1031]
  apps/methodologies/bold/rule-processors/mass/pick-up-move/src/lib/pick-up-move.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/pick-up-move/src/lib/pick-up-move.processor.ts
  libs/methodologies/bold/types/src/enum.types.ts
Labels: feature, priority: high

#38 feat: change geolocation-precision rules to accept a list of move type
  apps/methodologies/bold/rule-processors/mass/drop-off-geolocation-precision/src/lib/drop-off-geolocation-precision.processor.ts
  apps/methodologies/bold/rule-processors/mass/pick-up-geolocation-precision/src/lib/pick-up-geolocation-precision.e2e.spec.ts
  apps/methodologies/bold/rule-processors/mass/pick-up-geolocation-precision/src/lib/pick-up-geolocation-precision.processor.ts
  libs/methodologies/bold/processors/src/geolocation-precision-processor.spec.ts
  libs/methodologies/bold/processors/src/geolocation-precision-processor.ts
Labels: feature

#44 feat(rule): update rule to get events with a valid move-type value [CARROT-1037]
  apps/methodologies/bold/rule-processors/mass/vehicle-description/README.md
  apps/methodologies/bold/rule-processors/mass/vehicle-description/src/lib/vehicle-description.processor.e2e.spec.ts
  apps/methodologies/bold/rule-processors/mass/vehicle-description/src/lib/vehicle-description.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/vehicle-description/src/lib/vehicle-description.processor.ts
Labels: feature

#41 feat(rule): update rule to get events with a valid move-type value [CARROT-1034]
  apps/methodologies/bold/rule-processors/mass/maximum-distance/README.md
  apps/methodologies/bold/rule-processors/mass/maximum-distance/src/lib/maximum-distance.processor.constants.ts
  apps/methodologies/bold/rule-processors/mass/maximum-distance/src/lib/maximum-distance.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/maximum-distance/src/lib/maximum-distance.processor.ts
Labels: feature

#43 feature/update driver internal id rule [CARROT-1036]
  apps/methodologies/bold/rule-processors/mass/driver-internal-id/README.md
  apps/methodologies/bold/rule-processors/mass/driver-internal-id/src/lib/driver-internal-id.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/driver-internal-id/src/lib/driver-internal-id.processor.ts
Labels: feature

#42 feat(rule): update rule to get events with a valid move-type value [CARROT-1035]
  apps/methodologies/bold/rule-processors/mass/vehicle-license-plate/src/lib/vehicle-license-plate.processor.e2e.spec.ts
  apps/methodologies/bold/rule-processors/mass/vehicle-license-plate/src/lib/vehicle-license-plate.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/vehicle-license-plate/src/lib/vehicle-license-plate.processor.ts
Labels: feature

#40 feat(rule): get evaluateEvent from events with valid move-type [CARROT-1032]
  apps/methodologies/bold/rule-processors/mass/same-source-and-pick-up-addresses/README.md
  apps/methodologies/bold/rule-processors/mass/same-source-and-pick-up-addresses/src/lib/same-source-and-pick-up-addresses.processor.e2e.spec.ts
  apps/methodologies/bold/rule-processors/mass/same-source-and-pick-up-addresses/src/lib/same-source-and-pick-up-addresses.processor.ts
  apps/methodologies/bold/rule-processors/mass/same-source-and-pick-up-addresses/src/lib/same-source-and-pick-up-addressess.processor.spec.ts
Labels: feature

#37 feat(rule): update has-cdf rule [CARROT-1039]
  apps/methodologies/bold/rule-processors/mass/has-cdf/README.md
  apps/methodologies/bold/rule-processors/mass/has-cdf/src/lib/has-cdf.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/has-cdf/src/lib/has-cdf.processor.ts
Labels: feature, priority: high

#46 feat(rule): update vehicle-type rule [CARROT-1038]
  apps/methodologies/bold/rule-processors/mass/vehicle-type/README.md
  apps/methodologies/bold/rule-processors/mass/vehicle-type/src/lib/vehicle-type.processor.e2e.spec.ts
  apps/methodologies/bold/rule-processors/mass/vehicle-type/src/lib/vehicle-type.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass/vehicle-type/src/lib/vehicle-type.processor.ts
  apps/methodologies/bold/rule-processors/mass/vehicle-type/src/lib/vehicle-type.stubs.ts
Labels: feature, priority: high

#47 chore: update the README of rules that were updated
  apps/methodologies/bold/rule-processors/mass/driver-internal-id/README.md
  apps/methodologies/bold/rule-processors/mass/event-value/README.md
  apps/methodologies/bold/rule-processors/mass/events-time-span/README.md
  apps/methodologies/bold/rule-processors/mass/mandatory-metadata/README.md
  apps/methodologies/bold/rule-processors/mass/maximum-distance/README.md
  apps/methodologies/bold/rule-processors/mass/pick-up-geolocation-precision/README.md
  apps/methodologies/bold/rule-processors/mass/same-source-and-pick-up-addresses/README.md
  apps/methodologies/bold/rule-processors/mass/vehicle-description/README.md
  apps/methodologies/bold/rule-processors/mass/vehicle-license-plate/README.md
  apps/methodologies/bold/rule-processors/mass/vehicle-type/README.md
Labels: chore
