Repository carrot-foundation/methodology-rules, pull requests merged in 2025-09, with the labels that each got.

#300 Add CloudWatch metrics library foundation
  .env-files/.env.test
  libs/shared/cloudwatch-metrics/eslint.config.js
  libs/shared/cloudwatch-metrics/jest.config.ts
  libs/shared/cloudwatch-metrics/package.json
  libs/shared/cloudwatch-metrics/project.json
  libs/shared/cloudwatch-metrics/src/cloudwatch-metrics.constants.ts
  libs/shared/cloudwatch-metrics/src/cloudwatch-metrics.service.spec.ts
  libs/shared/cloudwatch-metrics/src/cloudwatch-metrics.service.ts
  libs/shared/cloudwatch-metrics/src/index.ts
  libs/shared/cloudwatch-metrics/tsconfig.build.json
  libs/shared/cloudwatch-metrics/tsconfig.eslint.json
  libs/shared/cloudwatch-metrics/tsconfig.json
  libs/shared/cloudwatch-metrics/tsconfig.spec.json
  libs/shared/helpers/src/common.helpers.spec.ts
  libs/shared/helpers/src/common.helpers.ts
  package.json
  pnpm-lock.yaml
Labels: ⏳ Waiting for 2 reviewers, 30 min review

#301 [STACKED] Integrate CloudWatch metrics in document processor
  libs/methodologies/bold/rule-processors/mass-id/document-manifest-data/src/document-manifest-data.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/document-manifest-data/src/document-manifest-data.processor.ts
  tsconfig.paths.json
Labels: ⏳ Waiting for 1 reviewer, 10 min review, 🚨 1 Unresolved Thread(s)

#306 feat(rule): add number formatting to prevented-emissions output
  libs/methodologies/bold/rule-processors/mass-id/prevented-emissions/src/prevented-emissions.helpers.ts
  libs/methodologies/bold/rule-processors/mass-id/prevented-emissions/src/prevented-emissions.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/prevented-emissions/src/prevented-emissions.test-cases.ts
Labels: feature, 1 min review
