Repository carrot-foundation/methodology-rules, pull requests merged in 2025-07, with the labels that each got.

#278 Refactor helper to return newest emission and composting metrics instead the first found
  libs/methodologies/bold/rule-processors/mass-id/mass-id-sorting/src/mass-id-sorting.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/prevented-emissions/src/prevented-emissions.processor.ts
  libs/shared/methodologies/bold/getters/src/document.getters.spec.ts
  libs/shared/methodologies/bold/getters/src/document.getters.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-participant-homologation.stubs.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: ⏳ Waiting for 1 reviewer, 5 min review, refactoring

#279 Update emission metrics retrieval to use last year logic
  libs/methodologies/bold/rule-processors/mass-id/mass-id-sorting/src/mass-id-sorting.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/mass-id-sorting/src/mass-id-sorting.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/mass-id-sorting/src/mass-id-sorting.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/mass-id-sorting/src/mass-id-sorting.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/prevented-emissions/src/prevented-emissions.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/prevented-emissions/src/prevented-emissions.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/prevented-emissions/src/prevented-emissions.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/prevented-emissions/src/prevented-emissions.test-cases.ts
  libs/shared/methodologies/bold/getters/src/document.getters.spec.ts
  libs/shared/methodologies/bold/getters/src/document.getters.ts
Labels: ⏳ Waiting for 2 reviewers, 20 min review, 🚨 1 Unresolved Thread(s), refactoring

#280 Simplify year handling in emission metrics event retrieval
  libs/methodologies/bold/rule-processors/mass-id/mass-id-sorting/src/mass-id-sorting.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/prevented-emissions/src/prevented-emissions.processor.ts
  libs/shared/methodologies/bold/getters/src/document.getters.spec.ts
  libs/shared/methodologies/bold/getters/src/document.getters.ts
Labels: 10 min review, refactoring

#283 Add a resourceName parameter to package-lambda to avoid being limited when definind rules name
  apps/methodologies/bold-carbon/rule-processors/mass-id/participant-accreditations-and-verifications-requirements/project.json
  nx.json
  scripts/package-lambda.sh
Labels: 1 min review, refactoring

#285 Move resource name handling from package to upload lambda scripts
  apps/methodologies/bold-carbon/rule-processors/mass-id/participant-accreditations-and-verifications-requirements/project.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/participant-accreditations-and-verifications-requirements/project.json
  nx.json
  scripts/package-lambda.sh
  scripts/upload-lambda.sh
Labels: ⏳ Waiting for 1 reviewer, 1 min review, 🚨 1 Unresolved Thread(s), refactoring

#286 Clean up RULE_NAME by removing methodologies and rule-processors prefixes
  scripts/upload-lambda.sh
Labels: ⏳ Waiting for 1 reviewer, 1 min review, refactoring

#288 feat(rule): add address field to rewards distribution results
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.helpers.spec.ts
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.helpers.ts
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.test-cases.ts
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.types.ts
  libs/methodologies/bold/rule-processors/mass-id-certificate/rewards-distribution/src/rewards-distribution.helpers.ts
  libs/methodologies/bold/rule-processors/mass-id-certificate/rewards-distribution/src/rewards-distribution.processor.ts
  libs/methodologies/bold/rule-processors/mass-id-certificate/rewards-distribution/src/rewards-distribution.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id-certificate/rewards-distribution/src/rewards-distribution.types.ts
  libs/shared/methodologies/bold/types/src/rewards-distribution.types.ts
Labels: feature, 10 min review, 5 min review
