Repository carrot-foundation/methodology-rules, pull requests merged in 2025-08, with the labels that each got.

#289 Add null safety and type conversion for reference year comparison
  libs/shared/methodologies/bold/getters/src/document.getters.ts
Labels: fix, 1 min review

#294 fix: get participant accreditation from actor relation
  libs/methodologies/bold/rule-processors/mass-id/geolocation-and-address-precision/src/geolocation-and-address-precision.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/geolocation-and-address-precision/src/geolocation-and-address-precision.helpers.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/geolocation-and-address-precision/src/geolocation-and-address-precision.helpers.ts
  libs/methodologies/bold/rule-processors/mass-id/geolocation-and-address-precision/src/geolocation-and-address-precision.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/geolocation-and-address-precision/src/geolocation-and-address-precision.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/geolocation-and-address-precision/src/geolocation-and-address-precision.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/geolocation-and-address-precision/src/geolocation-and-address-precision.test-cases.ts
Labels: ⏳ Waiting for 2 reviewers, 30 min review

#296 fix: update LicensePlate pattern to include space the format and adjust test cases accordingly
  libs/shared/helpers/src/is.typia.spec.ts
  libs/shared/types/src/utilities.types.ts
Labels: 1 min review

#297 chore: improve some error messages
  libs/methodologies/bold/rule-processors/mass-id/driver-identification/src/driver-identification.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/geolocation-and-address-precision/src/geolocation-and-address-precision.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/regional-waste-classification/src/regional-waste-classification.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/vehicle-identification/src/vehicle-identification.processor.ts
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#299 Add AI-powered validation with context prompts for manifest processors
  apps/methodologies/bold-carbon/rule-processors/mass-id/recycling-manifest-data/src/lambda.ts
  apps/methodologies/bold-carbon/rule-processors/mass-id/transport-manifest-data/src/lambda.ts
  apps/methodologies/bold-recycling/rule-processors/mass-id/recycling-manifest-data/src/lambda.ts
  apps/methodologies/bold-recycling/rule-processors/mass-id/transport-manifest-data/src/lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/document-manifest-data/src/document-manifest-data.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/document-manifest-data/src/document-manifest-data.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/document-manifest-data/src/document-manifest-data.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/document-manifest-data/src/document-manifest-data.processor.ts
  libs/shared/methodologies/ai-attachment-validator/src/ai-attachment-validator.service.spec.ts
  libs/shared/methodologies/ai-attachment-validator/src/ai-attachment-validator.service.ts
  libs/shared/methodologies/ai-attachment-validator/src/ai-prompts.constants.ts
  libs/shared/methodologies/ai-attachment-validator/src/index.ts
Labels: feature
