Repository carrot-foundation/methodology-rules, pull requests merged in 2025-02, with the labels that each got.

#115 chore: update .gitignore with Cursor-related files
  .gitignore
Labels: chore, 1 min review

#117 feat: update source code URL generation in upload-lambda script
  scripts/upload-lambda.sh
Labels: chore, 1 min review

#116 Update libs (major included)
  .jest/config/jest.base.config.ts
  .jest/config/setup-after-env.ts
  .tsconfig/tsconfig.spec.json
  apps/methodologies/bold-carbon-organic/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.dto.ts
  apps/methodologies/bold-carbon-organic/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.spec.ts
  apps/methodologies/bold-carbon-organic/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.ts
  apps/methodologies/bold-carbon-organic/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.typia.ts
  apps/methodologies/bold-carbon-organic/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.processor.e2e.spec.ts
  apps/methodologies/bold-carbon-organic/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.processor.spec.ts
  apps/methodologies/bold-carbon-organic/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.helpers.spec.ts
  apps/methodologies/bold-carbon-organic/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.processor.ts
  apps/methodologies/bold-carbon-organic/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.processor.typia.ts
  apps/methodologies/bold-carbon-organic/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.test.helpers.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.spec.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.typia.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.dto.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.spec.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.helpers.typia.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.processor.e2e.spec.ts
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.processor.spec.ts
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.helpers.spec.ts
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.processor.ts
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.processor.typia.ts
  apps/methodologies/bold/rule-processors/credit/rewards-distribution/src/lib/rewards-distribution.test.helpers.ts
  apps/methodologies/bold/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.spec.ts
  apps/methodologies/bold/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.ts
  apps/methodologies/bold/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.typia.ts
  jest.config.ts
  libs/methodologies/bold/recycling/organic/getters/src/event.getters.ts
  libs/methodologies/bold/recycling/organic/getters/src/event.getters.typia.ts
  libs/methodologies/bold/recycling/organic/io-helpers/src/document-helpers.typia.ts
  libs/methodologies/bold/recycling/organic/io-helpers/src/document-query.service.ts
  libs/methodologies/bold/recycling/organic/io-helpers/src/document-query.service.typia.ts
  libs/methodologies/bold/recycling/organic/io-helpers/src/document.helpers.ts
  libs/methodologies/bold/recycling/organic/predicates/src/event.predicates.ts
  libs/methodologies/bold/recycling/organic/predicates/src/event.predicates.typia.ts
  libs/shared/document/loader/src/document.repository.spec.ts
  libs/shared/helpers/src/index.ts
  libs/shared/helpers/src/is.typia.ts
  libs/shared/rule/result/src/rule-result.helpers.spec.ts
  libs/shared/rule/result/src/rule-result.helpers.ts
  libs/shared/rule/result/src/rule-result.typia.ts
  libs/shared/s3-bucket/src/s3-bucket.repository.spec.ts
  libs/shared/testing/src/matchers/index.ts
  libs/shared/testing/src/matchers/typia.matchers.ts
  package.json
  pnpm-lock.yaml
  tsconfig.base.json
  types/methodology-rules-jest-matchers/index.d.ts
Labels: ⏳ Waiting for 2 reviewers, 20 min review, refactoring

#121 [STACKED] feature/base processor error
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.errors.ts
  apps/methodologies/bold/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.errors.ts
  libs/shared/methodologies/bold/processors/src/base-processor.errors.spec.ts
  libs/shared/methodologies/bold/processors/src/base-processor.errors.ts
  libs/shared/methodologies/bold/processors/src/index.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 10 min review, 🚨 1 Unresolved Thread(s)

#123 feat(rule): add Mass ID audit eligibility check rule processor for Bold methodology
  .eslintrc.js
  libs/methodologies/bold/rule-processors/mass-id/.eslintrc.js
  libs/methodologies/bold/rule-processors/mass-id/jest.config.ts
  libs/methodologies/bold/rule-processors/mass-id/package.json
  libs/methodologies/bold/rule-processors/mass-id/project.json
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-period/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-period/project-period.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-period/project-period.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/tsconfig.eslint.json
  libs/methodologies/bold/rule-processors/mass-id/tsconfig.json
  libs/methodologies/bold/rule-processors/mass-id/tsconfig.spec.json
  libs/shared/methodologies/bold/predicates/src/event.predicates.spec.ts
  libs/shared/methodologies/bold/predicates/src/event.predicates.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
  libs/shared/types/src/methodology/methodology-enum.types.ts
  package.json
  pnpm-lock.yaml
  tsconfig.base.json
Labels: feature, ⏳ Waiting for 2 reviewers, 30 min review, 🚨 4 Unresolved Thread(s)

#124 [STACKED] feature/carbon audit eligibility check
  apps/methodologies/bold-carbon-organic/rule-processors/mass/project-period/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass/project-period/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass/project-period/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass/project-period/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass/project-period/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass/project-period/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass/project-period/src/lib/lambda.e2e.spec.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass/project-period/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass/project-period/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass/project-period/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass/project-period/tsconfig.spec.json
  libs/shared/methodologies/bold/testing/src/documents/approved-mass-document.ts
Labels: feature, ⏳ Waiting for 1 reviewer, 5 min review, 🚨 1 Unresolved Thread(s)

#129 feat(shared): add getOrDefault and getOrUndefined utility functions
  libs/shared/helpers/src/common.helpers.spec.ts
  libs/shared/helpers/src/common.helpers.ts
  libs/shared/types/src/index.ts
  libs/shared/types/src/primitives.types.ts
Labels: feature, ⏳ Waiting for 1 reviewer, 1 min review

#132 chore: remove mass certificate rule scope
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/src/lib/mass-audit-document-status.processor.e2e.spec.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/src/lib/mass-audit-document-status.processor.spec.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/src/lib/mass-audit-document-status.processor.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/mass-audit-document-status/tsconfig.spec.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/index.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.constants.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.helpers.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.e2e.spec.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.errors.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.spec.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.typia.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.stubs.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.types.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-certificate/rewards-distribution/tsconfig.spec.json
Labels: chore, ⏳ Waiting for 1 reviewer, 5 min review

#128 refactor: change nonEmptyString assert
  apps/methodologies/bold/rule-processors/credit/nft-metadata-selection/src/lib/nft-metadata-selection.types.ts
  libs/shared/methodologies/bold/testing/src/documents/approved-mass-document.ts
Labels: ⏳ Waiting for 1 reviewer, 1 min review

#135 chore: force update rule
  apps/methodologies/bold/rule-processors/mass/document-value/src/lib/document-value.processor.ts
Labels: ⏳ Waiting for 1 reviewer, 1 min review

#136 Revert "chore: force update rule"
  apps/methodologies/bold/rule-processors/mass/document-value/src/lib/document-value.processor.ts
Labels: ⏳ Waiting for 1 reviewer

#137 refactor(rule): restructure project period processor lambda implementation
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-period/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-period/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/project-period/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/project-period/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/project-period/src/lib/lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-period/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-period/project-period.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-period/project-period.lambda.ts
Labels: ⏳ Waiting for 1 reviewer, 1 min review, refactoring

#130 feature/check participants homologation
  apps/methodologies/bold/rule-processors/mass/pick-up-geolocation-precision/src/lib/pick-up-geolocation-precision.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/shared/methodologies/bold/helpers/.eslintrc.js
  libs/shared/methodologies/bold/helpers/jest.config.ts
  libs/shared/methodologies/bold/helpers/package.json
  libs/shared/methodologies/bold/helpers/project.json
  libs/shared/methodologies/bold/helpers/src/homologation-document.helpers.spec.ts
  libs/shared/methodologies/bold/helpers/src/homologation-document.helpers.ts
  libs/shared/methodologies/bold/helpers/src/index.ts
  libs/shared/methodologies/bold/helpers/tsconfig.build.json
  libs/shared/methodologies/bold/helpers/tsconfig.eslint.json
  libs/shared/methodologies/bold/helpers/tsconfig.json
  libs/shared/methodologies/bold/helpers/tsconfig.spec.json
  libs/shared/methodologies/bold/processors/src/geolocation-precision-processor.spec.ts
  libs/shared/methodologies/bold/processors/src/geolocation-precision-processor.ts
  libs/shared/methodologies/bold/processors/src/geolocation-precision.helpers.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
  libs/shared/rule/result/src/rule-result.helpers.ts
  tsconfig.base.json
Labels: feature, ⏳ Waiting for 2 reviewers, 30 min review, 🚨 10 Unresolved Thread(s)

#131 [STACKED] feature/bold check participants homologation
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/check-participants-homologation/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/check-participants-homologation/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/check-participants-homologation/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/check-participants-homologation/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/check-participants-homologation/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/check-participants-homologation/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/check-participants-homologation/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/check-participants-homologation/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/check-participants-homologation/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/check-participants-homologation/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/check-participants-homologation/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/check-participants-homologation/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/check-participants-homologation/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/check-participants-homologation/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/check-participants-homologation/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/check-participants-homologation/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/check-participants-homologation/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/check-participants-homologation/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/check-participants-homologation/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/check-participants-homologation/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/index.ts
Labels: feature, 30 min review

#133 feat(rule): add credit absence rule processor for Bold methodology
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/shared/methodologies/bold/matchers/src/document.matchers.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 20 min review, 🚨 6 Unresolved Thread(s)

#134 [STACKED] feature/bold credit absence
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/tcc-absence/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/tcc-absence/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/tcc-absence/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/tcc-absence/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/tcc-absence/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/tcc-absence/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/tcc-absence/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/tcc-absence/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/tcc-absence/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/tcc-absence/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/trc-absence/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/trc-absence/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/trc-absence/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/trc-absence/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/trc-absence/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/trc-absence/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/trc-absence/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/trc-absence/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/trc-absence/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/trc-absence/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/index.ts
Labels: feature, 20 min review

#138 refactor(rule): update credit absence processor to use credit subtype
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.ts
Labels: fix, ⏳ Waiting for 1 reviewer, 1 min review
