Repository carrot-foundation/methodology-rules, pull requests merged in 2025-03, with the labels that each got.

#140 refactor(shared): add BoldStubsBuilder for simplified test document generation
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.spec.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-stub.builder.ts
  libs/shared/methodologies/bold/testing/src/builders/index.ts
  libs/shared/methodologies/bold/testing/src/index.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 20 min review

#142 [STACKED] test/improve check participants homologation tests
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.processor.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-stub.builder.ts
Labels: ⏳ Waiting for 2 reviewers, 20 min review, refactoring

#145 chore: add Cursor MCP configuration file
  .cursor/mcp.json
Labels: chore, ⏳ Waiting for 1 reviewer, 1 min review

#143 chore: configure cacheable operations for improved build performance
  nx.json
Labels: chore, 1 min review

#150 feat(shared): add optional label to MethodologyDocumentEvent
  libs/shared/types/src/methodology/methodology-document-event.types.ts
  libs/shared/types/src/methodology/methodology-enum.types.ts
Labels: feature, 1 min review

#147 feature/check organic waste criteria rule
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/mass-definition/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/mass-definition/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/mass-definition/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/mass-definition/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/mass-definition/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/mass-definition/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/mass-definition/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/mass-definition/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/mass-definition/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/mass-definition/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/mass-definition/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/mass-definition/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/mass-definition/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/mass-definition/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/mass-definition/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/mass-definition/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/mass-definition/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/mass-definition/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/mass-definition/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/mass-definition/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.test-cases.ts
  libs/shared/methodologies/bold/matchers/src/document.matchers.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-stub.builder.ts
  libs/shared/methodologies/bold/testing/src/stubs/document.stubs.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 30 min review

#149 feature/waste origin identification
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/waste-origin-identification/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/waste-origin-identification/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/waste-origin-identification/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/waste-origin-identification/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/waste-origin-identification/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/waste-origin-identification/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/waste-origin-identification/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/waste-origin-identification/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/waste-origin-identification/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/waste-origin-identification/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/waste-origin-identification/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/waste-origin-identification/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/waste-origin-identification/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/waste-origin-identification/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/waste-origin-identification/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/waste-origin-identification/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/waste-origin-identification/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/waste-origin-identification/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/waste-origin-identification/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/waste-origin-identification/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/waste-origin-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/waste-origin-identification.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/waste-origin-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/waste-origin-identification.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/waste-origin-identification.test-cases.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
  libs/shared/types/src/methodology/methodology-enum.types.ts
Labels: feature, ⏳ Waiting for 1 reviewer, 30 min review, 🚨 1 Unresolved Thread(s)

#153 chore(rule): add mass ID rule generator script
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.lambda.e2e.spec.ts
  libs/shared/methodologies/bold/helpers/src/homologation-document.helpers.spec.ts
  package.json
  pnpm-lock.yaml
  tools/create-mass-id-rule.js
Labels: chore, ⏳ Waiting for 2 reviewers, 20 min review, 🚨 3 Unresolved Thread(s)

#155 feat(shared): implement getParticipantActorType function and related tests
  libs/shared/methodologies/bold/getters/src/document.getters.spec.ts
  libs/shared/methodologies/bold/getters/src/document.getters.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: feature, ⏳ Waiting for 1 reviewer, 20 min review, 🚨 1 Unresolved Thread(s)

#151 feature/recycler identification
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycler-identification/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycler-identification/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycler-identification/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycler-identification/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycler-identification/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycler-identification/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycler-identification/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycler-identification/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycler-identification/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycler-identification/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycler-identification/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycler-identification/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycler-identification/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycler-identification/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycler-identification/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycler-identification/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycler-identification/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycler-identification/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycler-identification/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycler-identification/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/recycler-identification/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/recycler-identification/recycler-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/recycler-identification/recycler-identification.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/recycler-identification/recycler-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/recycler-identification/recycler-identification.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/recycler-identification/recycler-identification.test-cases.ts
  libs/shared/methodologies/bold/predicates/src/event.predicates.spec.ts
  libs/shared/methodologies/bold/predicates/src/event.predicates.ts
  libs/shared/methodologies/bold/testing/src/stubs/document-event.stubs.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 20 min review, 🚨 1 Unresolved Thread(s)

#152 feature/hauler identification rule
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/hauler-identification/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/hauler-identification/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/hauler-identification/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/hauler-identification/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/hauler-identification/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/hauler-identification/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/hauler-identification/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/hauler-identification/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/hauler-identification/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/hauler-identification/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/hauler-identification/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/hauler-identification/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/hauler-identification/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/hauler-identification/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/hauler-identification/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/hauler-identification/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/hauler-identification/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/hauler-identification/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/hauler-identification/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/hauler-identification/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/hauler-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/hauler-identification.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/hauler-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/hauler-identification.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/hauler-identification.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/shared/methodologies/bold/predicates/src/event.predicate-factories.spec.ts
  libs/shared/methodologies/bold/predicates/src/event.predicate-factories.ts
  libs/shared/methodologies/bold/predicates/src/event.predicates.ts
  libs/shared/methodologies/bold/testing/src/stubs/document-event.stubs.ts
  libs/shared/methodologies/bold/types/src/document-event.types.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
  libs/shared/types/src/methodology/methodology-enum.types.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 30 min review, 🚨 7 Unresolved Thread(s)

#157 [STACKED] feature/update methodology document types
  libs/shared/types/src/methodology/methodology-document-event.types.ts
  libs/shared/types/src/methodology/methodology-document.types.ts
  libs/shared/types/src/methodology/methodology-enum.types.ts
Labels: chore, 1 min review, 🚨 1 Unresolved Thread(s)

#154 feature/vehicle identification
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/vehicle-identification/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/vehicle-identification/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/vehicle-identification/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/vehicle-identification/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/vehicle-identification/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/vehicle-identification/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/vehicle-identification/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/vehicle-identification/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/vehicle-identification/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/vehicle-identification/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/vehicle-identification/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/vehicle-identification/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/vehicle-identification/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/vehicle-identification/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/vehicle-identification/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/vehicle-identification/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/vehicle-identification/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/vehicle-identification/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/vehicle-identification/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/vehicle-identification/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.helpers.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.helpers.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.test-cases.ts
  libs/shared/methodologies/bold/predicates/src/event.predicate-factories.ts
  libs/shared/methodologies/bold/predicates/src/event.predicates.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
  libs/shared/types/src/methodology/methodology-document-event.types.ts
  libs/shared/types/src/methodology/methodology-document.types.ts
  libs/shared/types/src/methodology/methodology-enum.types.ts
  libs/shared/types/src/string.types.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 🚨 3 Unresolved Thread(s), 30 min review

#159 [STACKED] refactor/bold stubs builder
  .jest/config/jest.base.config.ts
  apps/methodologies/bold/rule-processors/mass/events-time-span/src/lib/events-time-span.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/check-participants-homologation/check-participants-homologation.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/hauler-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/hauler-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/hauler-identification.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/hauler-identification.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-period/project-period.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-period/project-period.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-period/project-period.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-period/project-period.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/recycler-identification/recycler-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/recycler-identification/recycler-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/recycler-identification/recycler-identification.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/time-interval-check/time-interval-check.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/time-interval-check/time-interval-check.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/waste-origin-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/waste-origin-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/waste-origin-identification.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/waste-origin-identification.test-cases.ts
  libs/shared/methodologies/bold/helpers/src/homologation-document.helpers.spec.ts
  libs/shared/methodologies/bold/helpers/src/homologation-document.helpers.ts
  libs/shared/methodologies/bold/io-helpers/src/document-query.service.spec.ts
  libs/shared/methodologies/bold/processors/src/geolocation-precision-processor.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-mass-id-audit.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-mass-id.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-participant-homologation.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-stub.builder.ts
  libs/shared/methodologies/bold/testing/src/builders/bold.builder.helpers.ts
  libs/shared/methodologies/bold/testing/src/builders/bold.stubs.types.ts
  libs/shared/methodologies/bold/testing/src/builders/index.ts
  libs/shared/methodologies/bold/testing/src/stubs/document-event.stubs.ts
  libs/shared/methodologies/bold/testing/src/stubs/document.stubs.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
  libs/shared/types/src/methodology/methodology-document-event.types.ts
  libs/shared/types/src/methodology/methodology-enum.types.ts
Labels: ⏳ Waiting for 2 reviewers, 30 min review, refactoring, 🚨 6 Unresolved Thread(s)

#161 [STACKED] feature/methodology geolocation precision
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/geolocation-precision/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/geolocation-precision/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/geolocation-precision/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/geolocation-precision/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/geolocation-precision/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/geolocation-precision/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/geolocation-precision/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/geolocation-precision/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/geolocation-precision/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/geolocation-precision/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/geolocation-precision/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/geolocation-precision/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/geolocation-precision/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/geolocation-precision/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/geolocation-precision/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/geolocation-precision/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/geolocation-precision/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/geolocation-precision/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/geolocation-precision/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/geolocation-precision/tsconfig.spec.json
Labels: feature, ⏳ Waiting for 2 reviewers, 10 min review

#163 feature/processor identification rule
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/processor-identification/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/processor-identification/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/processor-identification/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/processor-identification/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/processor-identification/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/processor-identification/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/processor-identification/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/processor-identification/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/processor-identification/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/processor-identification/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/processor-identification/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/processor-identification/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/processor-identification/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/processor-identification/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/processor-identification/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/processor-identification/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/processor-identification/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/processor-identification/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/processor-identification/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/processor-identification/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/processor-identification/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/processor-identification/processor-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/processor-identification/processor-identification.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/processor-identification/processor-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/processor-identification/processor-identification.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/processor-identification/processor-identification.test-cases.ts
  libs/shared/types/src/methodology/methodology-enum.types.ts
Labels: feature, ⏳ Waiting for 1 reviewer, 20 min review, 🚨 3 Unresolved Thread(s)

#165 feature/local waste classification
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/local-waste-classification/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/local-waste-classification/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/local-waste-classification/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/local-waste-classification/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/local-waste-classification/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/local-waste-classification/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/local-waste-classification/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/local-waste-classification/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/local-waste-classification/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/local-waste-classification/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/local-waste-classification/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/local-waste-classification/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/local-waste-classification/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/local-waste-classification/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/local-waste-classification/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/local-waste-classification/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/local-waste-classification/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/local-waste-classification/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/local-waste-classification/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/local-waste-classification/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/local-waste-classification/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/local-waste-classification/local-waste-classification.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/src/local-waste-classification/local-waste-classification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/local-waste-classification/local-waste-classification.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/local-waste-classification/local-waste-classification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/local-waste-classification/local-waste-classification.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/local-waste-classification/local-waste-classification.test-cases.ts
Labels: feature, ⏳ Waiting for 1 reviewer, 30 min review, 🚨 1 Unresolved Thread(s)

#166 chore: create the apply-methodology-rule script
  package.json
  tools/apply-methodology-rule.js
Labels: chore, ⏳ Waiting for 1 reviewer, 20 min review

#167 Update mass audit document matching criteria
  apps/methodologies/bold/rule-processors/mass-certificate/mass-audit-document/src/lib/mass-audit-document.processor.ts
  libs/shared/methodologies/bold/matchers/src/document.matchers.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: 1 min review, refactoring

#164 feature/driver identification
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/driver-identification/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/driver-identification/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/driver-identification/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/driver-identification/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/driver-identification/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/driver-identification/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/driver-identification/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/driver-identification/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/driver-identification/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/driver-identification/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/driver-identification/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/driver-identification/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/driver-identification/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/driver-identification/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/driver-identification/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/driver-identification/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/driver-identification/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/driver-identification/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/driver-identification/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/driver-identification/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/driver-identification/driver-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/driver-identification/driver-identification.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/driver-identification/driver-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/driver-identification/driver-identification.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/driver-identification/driver-identification.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/driver-identification/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 30 min review, 🚨 2 Unresolved Thread(s)

#170 feature/drop off at recycling facility
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/drop-off-at-recycling-facility/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/drop-off-at-recycling-facility/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/drop-off-at-recycling-facility/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/drop-off-at-recycling-facility/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/drop-off-at-recycling-facility/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/drop-off-at-recycling-facility/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/drop-off-at-recycling-facility/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/drop-off-at-recycling-facility/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/drop-off-at-recycling-facility/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/drop-off-at-recycling-facility/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/drop-off-at-recycling-facility/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/drop-off-at-recycling-facility/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/drop-off-at-recycling-facility/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/drop-off-at-recycling-facility/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/drop-off-at-recycling-facility/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/drop-off-at-recycling-facility/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/drop-off-at-recycling-facility/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/drop-off-at-recycling-facility/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/drop-off-at-recycling-facility/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/drop-off-at-recycling-facility/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/drop-off-at-recycling-facility/drop-off-at-recycling-facility.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/drop-off-at-recycling-facility/drop-off-at-recycling-facility.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/drop-off-at-recycling-facility/drop-off-at-recycling-facility.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/drop-off-at-recycling-facility/drop-off-at-recycling-facility.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/drop-off-at-recycling-facility/drop-off-at-recycling-facility.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/drop-off-at-recycling-facility/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-mass-id.stubs.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 30 min review, 🚨 2 Unresolved Thread(s)

#171 feature/project boundary
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-boundary/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-boundary/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-boundary/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-boundary/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-boundary/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-boundary/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-boundary/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-boundary/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-boundary/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/project-boundary/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-boundary/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-boundary/project-boundary.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-boundary/project-boundary.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-boundary/project-boundary.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-boundary/project-boundary.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-boundary/project-boundary.test-cases.ts
  libs/shared/methodologies/bold/testing/src/stubs/document.stubs.ts
  libs/shared/rule/standard-data-processor/src/rule-standard-data-processor.spec.ts
  libs/shared/rule/standard-data-processor/src/rule-standard-data-processor.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 30 min review, 🚨 1 Unresolved Thread(s)

#168 feat(rule): add transport-manifest processor and related components
  libs/methodologies/bold/rule-processors/mass-id/src/document-manifest/document-manifest.constants.ts
  libs/methodologies/bold/rule-processors/mass-id/src/document-manifest/document-manifest.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/document-manifest/document-manifest.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/document-manifest/document-manifest.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/document-manifest/document-manifest.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/document-manifest/document-manifest.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/document-manifest/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/shared/methodologies/bold/getters/src/event.getters.spec.ts
  libs/shared/methodologies/bold/getters/src/event.getters.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-mass-id.stubs.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 30 min review, 🚨 2 Unresolved Thread(s)

#169 [STACKED] feature/setup methodologies document manifest
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycling-manifest/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycling-manifest/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycling-manifest/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycling-manifest/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycling-manifest/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycling-manifest/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycling-manifest/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycling-manifest/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycling-manifest/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/recycling-manifest/tsconfig.spec.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/transport-manifest/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/transport-manifest/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/transport-manifest/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/transport-manifest/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/transport-manifest/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/transport-manifest/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/transport-manifest/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/transport-manifest/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/transport-manifest/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/transport-manifest/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycling-manifest/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycling-manifest/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycling-manifest/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycling-manifest/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycling-manifest/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycling-manifest/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycling-manifest/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycling-manifest/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycling-manifest/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/recycling-manifest/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/transport-manifest/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/transport-manifest/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/transport-manifest/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/transport-manifest/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/transport-manifest/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/transport-manifest/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/transport-manifest/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/transport-manifest/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/transport-manifest/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/transport-manifest/tsconfig.spec.json
Labels: feature, ⏳ Waiting for 1 reviewer, 20 min review

#174 [STACKED] refactor/bold stubs builder helper
  libs/shared/methodologies/bold/testing/src/builders/bold-stub.builder.ts
Labels: ⏳ Waiting for 1 reviewer, 20 min review, refactoring

#175 [STACKED] refactor/move license plate helper
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.helpers.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.helpers.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.processor.ts
  libs/shared/helpers/src/is.typia.spec.ts
  libs/shared/helpers/src/is.typia.ts
Labels: ⏳ Waiting for 1 reviewer, ⏳ Waiting for 2 reviewers, 20 min review, refactoring

#176 [STACKED] feature/weighing rule
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/weighing.constants.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/weighing.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/weighing.helpers.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/weighing.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/weighing.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/weighing.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/weighing.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/weighing.test-cases.ts
  libs/shared/methodologies/bold/getters/src/document.getters.spec.ts
  libs/shared/methodologies/bold/getters/src/document.getters.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-mass-id.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-participant-homologation.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/index.ts
Labels: feature, ⏳ Waiting for 1 reviewer, 30 min review, 🚨 1 Unresolved Thread(s)

#177 [STACKED] feature/methodologies weighing rule
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/weighing/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/weighing/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/weighing/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/weighing/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/weighing/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/weighing/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/weighing/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/weighing/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/weighing/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/weighing/tsconfig.spec.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/weighing/.eslintrc.js
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/weighing/README.md
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/weighing/jest.config.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/weighing/package.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/weighing/project.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/weighing/src/lambda.ts
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/weighing/tsconfig.build.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/weighing/tsconfig.eslint.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/weighing/tsconfig.json
  apps/methodologies/bold-recycling-organic/rule-processors/mass-id/weighing/tsconfig.spec.json
Labels: feature, ⏳ Waiting for 1 reviewer, 10 min review

#178 feature/avoided emissions
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/avoided-emissions/.eslintrc.js
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/avoided-emissions/README.md
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/avoided-emissions/jest.config.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/avoided-emissions/package.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/avoided-emissions/project.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/avoided-emissions/src/lambda.ts
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/avoided-emissions/tsconfig.build.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/avoided-emissions/tsconfig.eslint.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/avoided-emissions/tsconfig.json
  apps/methodologies/bold-carbon-organic/rule-processors/mass-id/avoided-emissions/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/avoided-emissions/avoided-emissions.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/src/avoided-emissions/avoided-emissions.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/avoided-emissions/avoided-emissions.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/avoided-emissions/avoided-emissions.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/avoided-emissions/avoided-emissions.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/avoided-emissions/avoided-emissions.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/avoided-emissions/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/geolocation-precision/geolocation-precision.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-sorting/mass-sorting.test-cases.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-mass-id.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-participant-homologation.stubs.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
  libs/shared/rule/result/src/rule-result.helpers.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 🚨 3 Unresolved Thread(s), 30 min review

#180 fix: change measurement unit to lowercase
  apps/methodologies/bold/rule-processors/mass/document-measurement-unit/README.md
  libs/methodologies/bold/rule-processors/mass-id/src/document-manifest/document-manifest.constants.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.processor.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-mass-id.stubs.ts
  libs/shared/methodologies/bold/testing/src/documents/approved-mass-document.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#179 Update document type structure and related tests
  apps/methodologies/bold/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.constants.ts
  apps/methodologies/bold/rule-processors/mass-certificate/rewards-distribution/src/lib/rewards-distribution.processor.e2e.spec.ts
  libs/shared/methodologies/bold/testing/src/stubs/document.stubs.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: 5 min review, refactoring

#181 feat(shared): add AWS HTTP service library with request signing functionality
  .env-files/.env.test
  libs/shared/aws-http/.eslintrc.js
  libs/shared/aws-http/jest.config.ts
  libs/shared/aws-http/package.json
  libs/shared/aws-http/project.json
  libs/shared/aws-http/src/aws-http.service.helpers.spec.ts
  libs/shared/aws-http/src/aws-http.service.helpers.ts
  libs/shared/aws-http/src/aws-http.service.spec.ts
  libs/shared/aws-http/src/aws-http.service.ts
  libs/shared/aws-http/src/index.ts
  libs/shared/aws-http/tsconfig.build.json
  libs/shared/aws-http/tsconfig.eslint.json
  libs/shared/aws-http/tsconfig.json
  libs/shared/aws-http/tsconfig.spec.json
  libs/shared/helpers/src/common.helpers.spec.ts
  libs/shared/helpers/src/common.helpers.ts
  libs/shared/types/src/common.types.ts
  package.json
  pnpm-lock.yaml
  tsconfig.base.json
Labels: feature, ⏳ Waiting for 1 reviewer, 30 min review

#182 [STACKED] feature/http request lib
  libs/shared/http-request/.eslintrc.js
  libs/shared/http-request/jest.config.ts
  libs/shared/http-request/package.json
  libs/shared/http-request/project.json
  libs/shared/http-request/src/http-request.spec.ts
  libs/shared/http-request/src/http-request.ts
  libs/shared/http-request/src/index.ts
  libs/shared/http-request/tsconfig.build.json
  libs/shared/http-request/tsconfig.eslint.json
  libs/shared/http-request/tsconfig.json
  libs/shared/http-request/tsconfig.spec.json
  tsconfig.base.json
Labels: feature, ⏳ Waiting for 2 reviewers, 20 min review

#183 [STACKED] feature/document seeds
  libs/shared/document/seeds/.eslintrc.js
  libs/shared/document/seeds/jest.config.ts
  libs/shared/document/seeds/package.json
  libs/shared/document/seeds/project.json
  libs/shared/document/seeds/src/document.seeds.ts
  libs/shared/document/seeds/src/index.ts
  libs/shared/document/seeds/tsconfig.build.json
  libs/shared/document/seeds/tsconfig.eslint.json
  libs/shared/document/seeds/tsconfig.json
  libs/shared/document/seeds/tsconfig.spec.json
  libs/shared/types/src/methodology/methodology-document.types.ts
  tsconfig.base.json
Labels: feature, ⏳ Waiting for 2 reviewers, 10 min review

#184 feature/audit api
  .env-files/.env.test
  .github/workflows/backend-check.yaml
  libs/shared/document/seeds/project.json
  libs/shared/methodologies/audit-api/.eslintrc.js
  libs/shared/methodologies/audit-api/jest.config.ts
  libs/shared/methodologies/audit-api/package.json
  libs/shared/methodologies/audit-api/project.json
  libs/shared/methodologies/audit-api/src/audit-api.constants.spec.ts
  libs/shared/methodologies/audit-api/src/audit-api.constants.ts
  libs/shared/methodologies/audit-api/src/audit-api.service.e2e.spec.ts
  libs/shared/methodologies/audit-api/src/audit-api.service.spec.ts
  libs/shared/methodologies/audit-api/src/audit-api.service.ts
  libs/shared/methodologies/audit-api/src/audit-api.typia.ts
  libs/shared/methodologies/audit-api/src/audit.api.dto.ts
  libs/shared/methodologies/audit-api/src/index.ts
  libs/shared/methodologies/audit-api/tsconfig.build.json
  libs/shared/methodologies/audit-api/tsconfig.eslint.json
  libs/shared/methodologies/audit-api/tsconfig.json
  libs/shared/methodologies/audit-api/tsconfig.spec.json
  tsconfig.base.json
Labels: feature, ⏳ Waiting for 2 reviewers, 20 min review, 🚨 3 Unresolved Thread(s)
