Repository carrot-foundation/methodology-rules, pull requests merged in 2025-05, with the labels that each got.

#221 chore/update bold builder
  libs/methodologies/bold/rule-processors/mass-id/src/avoided-emissions/avoided-emissions.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/avoided-emissions/avoided-emissions.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/avoided-emissions/avoided-emissions.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/composting-cycle-timeframe/composting-cycle-timeframe.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/document-manifest/document-manifest.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/document-manifest/document-manifest.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/driver-identification/driver-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/driver-identification/driver-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/drop-off-at-recycling-facility/drop-off-at-recycling-facility.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/drop-off-at-recycling-facility/drop-off-at-recycling-facility.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/geolocation-precision/geolocation-precision.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/geolocation-precision/geolocation-precision.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/geolocation-precision/geolocation-precision.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/hauler-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/local-waste-classification/local-waste-classification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/local-waste-classification/local-waste-classification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-sorting/mass-sorting.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-sorting/mass-sorting.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-sorting/mass-sorting.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/participant-homologations/participant-homologations.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/processor-identification/processor-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-boundary/project-boundary.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-boundary/project-boundary.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/recycler-identification/recycler-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/uniqueness-check/uniqueness-check.helpers.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/uniqueness-check/uniqueness-check.helpers.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/uniqueness-check/uniqueness-check.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/uniqueness-check/uniqueness-check.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/uniqueness-check/uniqueness-check.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/waste-origin-identification.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/weighing.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/weighing.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/weighing/weighing.test-cases.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-certificate.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-credits.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-stub.builder.ts
  libs/shared/methodologies/bold/testing/src/builders/index.ts
Labels: chore, ⏳ Waiting for 2 reviewers, 30 min review, 🚨 4 Unresolved Thread(s)

#216 feature/mass id rewards distribution
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.constants.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.helpers.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.types.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
  libs/shared/methodologies/bold/types/src/index.ts
  libs/shared/methodologies/bold/types/src/rewards-distribution.types.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 30 min review, 🚨 6 Unresolved Thread(s)

#217 [STACKED] feature/methodologies rewards distribution
  apps/methodologies/bold-carbon/rule-processors/mass-id/rewards-distribution/.eslintrc.js
  apps/methodologies/bold-carbon/rule-processors/mass-id/rewards-distribution/README.md
  apps/methodologies/bold-carbon/rule-processors/mass-id/rewards-distribution/jest.config.ts
  apps/methodologies/bold-carbon/rule-processors/mass-id/rewards-distribution/package.json
  apps/methodologies/bold-carbon/rule-processors/mass-id/rewards-distribution/project.json
  apps/methodologies/bold-carbon/rule-processors/mass-id/rewards-distribution/src/lambda.ts
  apps/methodologies/bold-carbon/rule-processors/mass-id/rewards-distribution/tsconfig.build.json
  apps/methodologies/bold-carbon/rule-processors/mass-id/rewards-distribution/tsconfig.eslint.json
  apps/methodologies/bold-carbon/rule-processors/mass-id/rewards-distribution/tsconfig.json
  apps/methodologies/bold-carbon/rule-processors/mass-id/rewards-distribution/tsconfig.spec.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/rewards-distribution/.eslintrc.js
  apps/methodologies/bold-recycling/rule-processors/mass-id/rewards-distribution/README.md
  apps/methodologies/bold-recycling/rule-processors/mass-id/rewards-distribution/jest.config.ts
  apps/methodologies/bold-recycling/rule-processors/mass-id/rewards-distribution/package.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/rewards-distribution/project.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/rewards-distribution/src/lambda.ts
  apps/methodologies/bold-recycling/rule-processors/mass-id/rewards-distribution/tsconfig.build.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/rewards-distribution/tsconfig.eslint.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/rewards-distribution/tsconfig.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/rewards-distribution/tsconfig.spec.json
  tools/apply-methodology-rule.js
Labels: feature, ⏳ Waiting for 2 reviewers, 10 min review

#224 refactor/load parent document
  libs/methodologies/bold/rule-processors/mass-id/src/composting-cycle-timeframe/composting-cycle-timeframe.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/document-manifest/document-manifest.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/driver-identification/driver-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/drop-off-at-recycling-facility/drop-off-at-recycling-facility.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/hauler-identification/hauler-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/local-waste-classification/local-waste-classification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/mass-definition/mass-definition.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/processor-identification/processor-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-boundary/project-boundary.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/project-period/project-period.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/recycler-identification/recycler-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/uniqueness-check/uniqueness-check.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/vehicle-identification/vehicle-identification.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/waste-origin-identification/waste-origin-identification.processor.spec.ts
  libs/shared/methodologies/bold/io-helpers/src/document.helpers.spec.ts
  libs/shared/methodologies/bold/io-helpers/src/document.helpers.ts
  libs/shared/methodologies/bold/io-helpers/src/testing.helpers.ts
  libs/shared/methodologies/bold/processors/src/parent-document-rule-processor.spec.ts
  libs/shared/methodologies/bold/processors/src/parent-document-rule-processor.ts
  tools/create-rule.js
Labels: ⏳ Waiting for 1 reviewer, 5 min review, refactoring

#222 feature/credits rewards distribution
  libs/methodologies/bold/rule-processors/credits/.eslintrc.js
  libs/methodologies/bold/rule-processors/credits/jest.config.ts
  libs/methodologies/bold/rule-processors/credits/package.json
  libs/methodologies/bold/rule-processors/credits/project.json
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/index.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.errors.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.helpers.spec.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.helpers.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.lambda.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.processor.spec.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.processor.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.test-cases.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.types.ts
  libs/methodologies/bold/rule-processors/credits/tsconfig.eslint.json
  libs/methodologies/bold/rule-processors/credits/tsconfig.json
  libs/methodologies/bold/rule-processors/credits/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.constants.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/rewards-distribution/rewards-distribution.types.ts
  libs/shared/methodologies/bold/matchers/src/document.matchers.spec.ts
  libs/shared/methodologies/bold/matchers/src/document.matchers.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-certificate.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-credits.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-stub.builder.ts
  libs/shared/methodologies/bold/testing/src/builders/index.ts
  libs/shared/methodologies/bold/testing/src/stubs/document.stubs.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
  libs/shared/methodologies/bold/types/src/rewards-distribution.types.ts
Labels: feature, ⏳ Waiting for 2 reviewers, 30 min review

#223 [STACKED] feature/methodologies credits rewards distribution
  apps/methodologies/bold-carbon/rule-processors/credits/rewards-distribution/.eslintrc.js
  apps/methodologies/bold-carbon/rule-processors/credits/rewards-distribution/README.md
  apps/methodologies/bold-carbon/rule-processors/credits/rewards-distribution/jest.config.ts
  apps/methodologies/bold-carbon/rule-processors/credits/rewards-distribution/package.json
  apps/methodologies/bold-carbon/rule-processors/credits/rewards-distribution/project.json
  apps/methodologies/bold-carbon/rule-processors/credits/rewards-distribution/src/lambda.ts
  apps/methodologies/bold-carbon/rule-processors/credits/rewards-distribution/tsconfig.build.json
  apps/methodologies/bold-carbon/rule-processors/credits/rewards-distribution/tsconfig.eslint.json
  apps/methodologies/bold-carbon/rule-processors/credits/rewards-distribution/tsconfig.json
  apps/methodologies/bold-carbon/rule-processors/credits/rewards-distribution/tsconfig.spec.json
  apps/methodologies/bold-recycling/rule-processors/credits/rewards-distribution/.eslintrc.js
  apps/methodologies/bold-recycling/rule-processors/credits/rewards-distribution/README.md
  apps/methodologies/bold-recycling/rule-processors/credits/rewards-distribution/jest.config.ts
  apps/methodologies/bold-recycling/rule-processors/credits/rewards-distribution/package.json
  apps/methodologies/bold-recycling/rule-processors/credits/rewards-distribution/project.json
  apps/methodologies/bold-recycling/rule-processors/credits/rewards-distribution/src/lambda.ts
  apps/methodologies/bold-recycling/rule-processors/credits/rewards-distribution/tsconfig.build.json
  apps/methodologies/bold-recycling/rule-processors/credits/rewards-distribution/tsconfig.eslint.json
  apps/methodologies/bold-recycling/rule-processors/credits/rewards-distribution/tsconfig.json
  apps/methodologies/bold-recycling/rule-processors/credits/rewards-distribution/tsconfig.spec.json
  libs/methodologies/bold/rule-processors/credits/src/index.ts
  tsconfig.base.json
Labels: feature, ⏳ Waiting for 2 reviewers, 10 min review

#225 refactor/update credit absence rule
  apps/methodologies/bold-carbon/rule-processors/mass-id/certificate-uniquiness-check/.eslintrc.js
  apps/methodologies/bold-carbon/rule-processors/mass-id/certificate-uniquiness-check/README.md
  apps/methodologies/bold-carbon/rule-processors/mass-id/certificate-uniquiness-check/jest.config.ts
  apps/methodologies/bold-carbon/rule-processors/mass-id/certificate-uniquiness-check/package.json
  apps/methodologies/bold-carbon/rule-processors/mass-id/certificate-uniquiness-check/project.json
  apps/methodologies/bold-carbon/rule-processors/mass-id/certificate-uniquiness-check/src/lambda.ts
  apps/methodologies/bold-carbon/rule-processors/mass-id/certificate-uniquiness-check/tsconfig.build.json
  apps/methodologies/bold-carbon/rule-processors/mass-id/certificate-uniquiness-check/tsconfig.eslint.json
  apps/methodologies/bold-carbon/rule-processors/mass-id/certificate-uniquiness-check/tsconfig.json
  apps/methodologies/bold-carbon/rule-processors/mass-id/certificate-uniquiness-check/tsconfig.spec.json
  apps/methodologies/bold-carbon/rule-processors/mass-id/tcc-absence/src/lambda.ts
  apps/methodologies/bold-recycling/rule-processors/mass-id/certificate-uniqueness-check/.eslintrc.js
  apps/methodologies/bold-recycling/rule-processors/mass-id/certificate-uniqueness-check/README.md
  apps/methodologies/bold-recycling/rule-processors/mass-id/certificate-uniqueness-check/jest.config.ts
  apps/methodologies/bold-recycling/rule-processors/mass-id/certificate-uniqueness-check/package.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/certificate-uniqueness-check/project.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/certificate-uniqueness-check/src/lambda.ts
  apps/methodologies/bold-recycling/rule-processors/mass-id/certificate-uniqueness-check/tsconfig.build.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/certificate-uniqueness-check/tsconfig.eslint.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/certificate-uniqueness-check/tsconfig.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/certificate-uniqueness-check/tsconfig.spec.json
  apps/methodologies/bold-recycling/rule-processors/mass-id/trc-absence/src/lambda.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.processor.spec.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.processor.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/certificate-uniqueness-check.constants.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/certificate-uniqueness-check.helpers.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/certificate-uniqueness-check.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/certificate-uniqueness-check.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/certificate-uniqueness-check.processor.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/certificate-uniqueness-check.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/certificate-uniqueness-check.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/certificate-uniqueness-check.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/credit-absence.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/credit-absence/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/index.ts
  libs/methodologies/bold/rule-processors/mass-id/src/uniqueness-check/uniqueness-check.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/src/uniqueness-check/uniqueness-check.test-cases.ts
  libs/shared/methodologies/bold/matchers/src/document.matchers.spec.ts
  libs/shared/methodologies/bold/matchers/src/document.matchers.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-mass-id-audit.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-stub.builder.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
  libs/shared/types/src/methodology/methodology-document.types.ts
  libs/shared/types/src/methodology/methodology-enum.types.ts
Labels: ⏳ Waiting for 2 reviewers, 30 min review, refactoring

#228 chore: add Carrot Methodology Rule Assistant and Nx guidelines
  .cursor/rules/carrot-methodology-rules.mdc
  .cursor/rules/nx-rules.mdc
  .vscode/settings.json
Labels: chore, 1 min review, 🚨 1 Unresolved Thread(s)

#230 feature/credits to credit order
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.errors.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.processor.ts
  libs/methodologies/bold/rule-processors/credits/src/rewards-distribution/rewards-distribution.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/certificate-uniqueness-check.constants.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/certificate-uniqueness-check.processor.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/src/certificate-uniqueness-check/certificate-uniqueness-check.processor.ts
  libs/shared/methodologies/bold/matchers/src/document.matchers.spec.ts
  libs/shared/methodologies/bold/matchers/src/document.matchers.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-credit-order.stubs.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-stub.builder.ts
  libs/shared/methodologies/bold/testing/src/builders/index.ts
  libs/shared/methodologies/bold/testing/src/stubs/document.stubs.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: chore, ⏳ Waiting for 1 reviewer, 5 min review

#241 feat(nx): enable nx powerpack s3 cache
  .github/actions/install-node-dependencies/action.yaml
  .github/actions/prepare-to-run-nx/action.yaml
  .github/workflows/backend-check.yaml
  .github/workflows/check-and-deploy.yaml
  .github/workflows/deploy.yaml
  nx.json
  package.json
  pnpm-lock.yaml
Labels: enhancement, 🚨 3 Unresolved Thread(s), 5 min review

#242 fix(shared): update slack webhook configuration
  .github/workflows/backend-check.yaml
  .github/workflows/deploy.yaml
Labels: bug, ⏳ Waiting for 1 reviewer, 1 min review

#243 refactor(shared): remove unused code
  libs/methodologies/bold/rule-processors/mass-id/certificate-uniqueness-check/src/certificate-uniqueness-check.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/participant-homologations/src/participant-homologations.processor.ts
  libs/shared/helpers/src/array.helpers.spec.ts
  libs/shared/helpers/src/array.helpers.ts
  libs/shared/helpers/src/math.helpers.spec.ts
  libs/shared/helpers/src/math.helpers.ts
  libs/shared/helpers/src/string.helpers.spec.ts
  libs/shared/helpers/src/string.helpers.ts
  libs/shared/methodologies/bold/testing/src/stubs/document.stubs.ts
  libs/shared/testing/src/helpers/index.ts
  libs/shared/testing/src/helpers/metadata.helpers.ts
  libs/shared/testing/src/stubs/__tests__/array.stubs.spec.ts
  libs/shared/testing/src/stubs/array.stubs.ts
  libs/shared/types/src/common.types.ts
  libs/shared/types/src/methodology/methodology-enum.types.ts
  libs/shared/types/src/utils.types.ts
Labels: enhancement, ⏳ Waiting for 2 reviewers, 5 min review

#245 feat(script): update rule creation command and docs
  .cursor/rules/nx-rules.mdc
  eslint.config.js
  libs/shared/app/types/project.json
  libs/shared/aws-http/project.json
  libs/shared/document/loader/project.json
  libs/shared/document/seeds/project.json
  libs/shared/helpers/project.json
  libs/shared/http-request/project.json
  libs/shared/lambda/types/project.json
  libs/shared/lambda/wrapper/project.json
  libs/shared/methodologies/audit-api/project.json
  libs/shared/methodologies/bold/getters/project.json
  libs/shared/methodologies/bold/helpers/project.json
  libs/shared/methodologies/bold/io-helpers/project.json
  libs/shared/methodologies/bold/matchers/project.json
  libs/shared/methodologies/bold/predicates/project.json
  libs/shared/methodologies/bold/processors/project.json
  libs/shared/methodologies/bold/testing/project.json
  libs/shared/methodologies/bold/types/project.json
  libs/shared/methodologies/bold/utils/project.json
  libs/shared/rule/result/project.json
  libs/shared/rule/standard-data-processor/project.json
  libs/shared/rule/types/project.json
  libs/shared/s3-bucket/project.json
  libs/shared/testing/project.json
  libs/shared/types/project.json
  package.json
  pnpm-lock.yaml
Labels: feature, ⏳ Waiting for 2 reviewers, 10 min review

#248 fix(rule): enhance certificate uniqueness check handler with recycled ID and methodology slug
  apps/methodologies/bold-recycling/rule-processors/mass-id/certificate-uniqueness-check/src/lambda.ts
Labels: fix, 1 min review

#249 chore: add @nx/powerpack-license and @nx/powerpack-s3-cache
  package.json
  pnpm-lock.yaml
Labels: fix, ⏳ Waiting for 1 reviewer, 1 min review

#251 chore: remove temporary log statement from mass-id-definition.lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/mass-id-definition/src/mass-id-definition.lambda.ts
Labels: chore

#252 fix: remove unnecessary environment and handle aws credentials in deploy
  .github/actions/prepare-to-run-nx/action.yaml
  .github/workflows/backend-check.yaml
  .github/workflows/deploy.yaml
Labels: fix, ⏳ Waiting for 1 reviewer, 1 min review

#253 chore: remove temporary log statement from mass-id-definition.lambda.ts
  .github/workflows/check-and-deploy.yaml
  libs/methodologies/bold/rule-processors/mass-id/mass-id-definition/src/mass-id-definition.lambda.ts
Labels: chore, ⏳ Waiting for 1 reviewer, 1 min review

#254 fix/prepare to run nx
  .github/actions/prepare-to-run-nx/action.yaml
  libs/methodologies/bold/rule-processors/mass-id/mass-id-definition/src/mass-id-definition.lambda.ts
Labels: fix, ⏳ Waiting for 1 reviewer, 1 min review

#255 chore: update AWS bucket name and enhance prepare-to-run-nx action with environment input
  .github/actions/prepare-to-run-nx/action.yaml
  .github/workflows/backend-check.yaml
  .github/workflows/check-and-deploy.yaml
  .github/workflows/deploy.yaml
  nx.json
Labels: feature, 5 min review

#256 feat: update rewards distribution handlers to accept GAS_ID and RECYCLED_ID
  apps/methodologies/bold-carbon/rule-processors/credit-order/rewards-distribution/src/lambda.ts
  apps/methodologies/bold-recycling/rule-processors/credit-order/rewards-distribution/src/lambda.ts
  libs/methodologies/bold/rule-processors/mass-id/mass-id-definition/src/mass-id-definition.lambda.ts
Labels: fix, 1 min review

#258 fix: update rewards distribution to use CREDIT_UNIT_PRICE and adjust related error messages
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.errors.ts
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.processor.ts
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.test-cases.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-credit-order.stubs.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
Labels: fix, 1 min review

#259 chore: add USD suffix on credit price
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.helpers.spec.ts
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.helpers.ts
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.processor.spec.ts
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.processor.ts
  libs/methodologies/bold/rule-processors/credit-order/rewards-distribution/src/rewards-distribution.test-cases.ts
  libs/shared/helpers/src/assert.typia.spec.ts
  libs/shared/helpers/src/assert.typia.ts
  libs/shared/helpers/src/index.ts
Labels: ⏳ Waiting for 2 reviewers, 10 min review, 🚨 1 Unresolved Thread(s)

#260 feat: add valuePrefix and valueSuffix to MethodologyDocumentEventAttribute
  libs/shared/types/src/methodology/methodology-document-event.types.ts
Labels: feature, ⏳ Waiting for 1 reviewer, 1 min review

#261 fix(rule): update avoided emissions processor and test cases for new baseline and subtype logic
  libs/methodologies/bold/rule-processors/mass-id/avoided-emissions/src/README.md
  libs/methodologies/bold/rule-processors/mass-id/avoided-emissions/src/avoided-emissions.constants.ts
  libs/methodologies/bold/rule-processors/mass-id/avoided-emissions/src/avoided-emissions.errors.ts
  libs/methodologies/bold/rule-processors/mass-id/avoided-emissions/src/avoided-emissions.helpers.ts
  libs/methodologies/bold/rule-processors/mass-id/avoided-emissions/src/avoided-emissions.lambda.e2e.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/avoided-emissions/src/avoided-emissions.processor.spec.ts
  libs/methodologies/bold/rule-processors/mass-id/avoided-emissions/src/avoided-emissions.processor.ts
  libs/methodologies/bold/rule-processors/mass-id/avoided-emissions/src/avoided-emissions.test-cases.ts
  libs/methodologies/bold/rule-processors/mass-id/avoided-emissions/src/avoided-emissions.types.ts
  libs/methodologies/bold/rule-processors/mass-id/avoided-emissions/src/avoided-emissions.typia.ts
  libs/shared/methodologies/bold/testing/src/builders/bold-participant-homologation.stubs.ts
  libs/shared/methodologies/bold/types/src/enum.types.ts
  libs/shared/types/src/methodology/methodology-enum.types.ts
Labels: ⏳ Waiting for 2 reviewers, 20 min review, 🚨 1 Unresolved Thread(s)

#263 chore: add temporary log for debugging purposes
  apps/methodologies/bold-carbon/rule-processors/mass-id/certificate-uniquiness-check/src/lambda.ts
Labels: chore
